[package]
name = "flowtest1"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
device_query = "2.0.0"
keycode = "0.4.0"